//Util to incorporate the parameters in string
module.exports.format = (...args) => args.shift().replace(/%s/g, x => args.shift());

//RFQ notication Strings
module.exports.RFQLeadNotification = "A lead with refId: %s is generated for you by %s.";
module.exports.RFQLeadAckNotification = "The lead with refId: %s,  generated by you is acknowledged by %s";
